Added Checks to Email Confirmation Page. Added Notification in Forgot…
soft-eng-practicum/NeuroSimHub pull request #56
Opened 2023-06-09 09:35 UTC by KshitizSareen

… Password page, and added notification stating confirmation email has been sent during registration.

2023-06-11 22:48 UTC, cengique requested changes
Minor request to fix message

2023-06-11 22:48 UTC, cengique commented on src/Analysim.Web/ClientApp/src/app/register/register.component.ts
> +        this.notfi.showSuccess('Account has been registered. A confirmation email has been sent for email verification.', 'Registration');
Can you change this message to: "Your account has been registered and a verification email has been sent to your address. Before you can login, you must confirm your account by clicking the link in this email."

2023-06-12 16:35 UTC, KshitizSareen commented on src/Analysim.Web/ClientApp/src/app/register/register.component.ts
> +        this.notfi.showSuccess('Account has been registered. A confirmation email has been sent for email verification.', 'Registration');
I have changed the message.

Thanks.

2023-06-12 21:10 UTC, cengique approved these changes

2023-06-12 21:11 UTC, merged